# import = [ "~/.config/alacritty/everforest_dark.toml" ]
import = [ "~/.config/alacritty/theme.toml" ]
# import = [ "~/.config/alacritty/base16.toml" ]

[env]
# TERM = "alacritty"
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[shell]
program = "/usr/bin/bash"

[window]
title = "Alacritty"
dimensions = { columns = 80, lines = 24}
padding = { x = 10, y = 10 }
decorations = "Full"
opacity = 1

[font]
# change to Ubuntu Mono maybe, default is monospace
# normal = { family="Ubuntu Mono", style="Regular" } 
# normal = { family="monospace", style="Regular" } 
normal = { family="Iosevka Extended Oblique", style="Regular" } 
# normal = { family="Noto Mono", style="Regular" } 
bold = { style="Bold" }
italic = { style="Italic" }
bold_italic = { style="Bold Italic" }
size = 12.0

[colors]
#primary = { foreground = "#d8d8d8", background = "#181818", dim_foreground = "#828482", bright_foreground = "None" }
cursor = { text = "CellBackground", cursor = "CellForeground"}
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground"}

#normal = { black="#181818", red="#ac4242", green="#90a959", yellow="#f4bf75", blue="#6a9fb5", cyan="#75b5aa", white="#d8d8d8" }

#bright  = { black = "#6b6b6b", red = "#c55555", green = "#aac474", yellow = "#feca88", blue = "#82b8c8", magenta = "#c28cb8", cyan = "#93d3c3", white = "#f8f8f8" }

#dim = { black = "#0f0f0f", red = "#712b2b", green = "#5f6f3a", yellow = "#a17e4d", blue = "#456877", magenta = "#704d68", cyan = "#4d7770", white = "#8e8e8e" }

transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Block", blinking = "Off" }
blink_interval = 500
blink_timeout = 0

[debug]
render_timer = false
