[colors]
primary = { foreground = "#d3c6aa", background = "#2d353b", dim_foreground = "#83c092", bright_foreground = "None" }

normal = { black = "#475258", red = "#e67e80", green = "#a7c080", yellow = "#dbbc7f", blue = "#7fbbb3", cyan = "#d699b6", white = "#83c092" }

bright = { black = "#475258", red = "#e67e80", green = "#a7c080", yellow = "#dbbc7f", blue = "#7fbbb3", magenta = "#d699b6", cyan = "#83c092", white = "#d3c6aa" }
