icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#121212"
idle_fg = "#d6cfd6"

info_bg = "#121212"
info_fg = "#d81860"

good_bg = "#121212"
good_fg = "#859900"

warning_bg = "#b58900"
warning_fg = "#002b36"

critical_bg = "#dc322f"
critical_fg = "#002b36"

# separator = "\ue0b2"
# separator_bg = "auto"
# separator_fg = "auto"

[icons]
icons = "awesome5"
#icons = "none"
[icons.overrides]
#bat = ["|E|", "|_|", "|=|", "|F|"]
#bat_charging = "|^| "

[[block]]
block = "tea_timer"
increment = 60
done_cmd = "notify-send -t 8000 -u critical 'TIMER END.\nTIMER END.\nTIMER END.'"

[[block]]
block = "time"
interval = 5
# format = " $timestamp.datetime(f:'%-I:%M %p %a, %b %d %Y') "
# format = " $timestamp.datetime(f:'%:z / %-I:%M %p %a, %m-%d-%Y') "
format = " $timestamp.datetime(f:'%:z / %Y-%m-%d(%w) %H:%M') "

# print(datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'))

#[[block]]
#block = "weather

[[block]]
block = "net"
#format = " $icon $ssid $signal_strength "
format = " $icon { $ssid $signal_strength |Wired connection} "
[[block.click]]
button = "right"
cmd = "alacritty -e nmtui"

[[block]]
block = "battery"
device = "BAT0"
format = " $icon $percentage {$time $power} "
full_format = " $icon "
empty_format = ""
# if below
info = 0
# triggers if above
good = 100
# if below
warning = 0
critical = -1

[[block]]
block = "battery"
device = "BAT1"
format = " $icon $percentage {$time $power} "
full_format = " $icon "
empty_format = ""
# if below
info = 60
# triggers if above
good = 100
# if below
warning = 40
critical = 20

[[block]]
block = "load"
format = " $icon $1m.eng(w:4) $5m.eng(w:4) $15m.eng(w:4) "
info = 0.3
warning = 0.6
critical = 0.9

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 120
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "memory"
#format = " $icon $mem_used /$mem_avail "
format = " $icon $mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi)($mem_used_percents.eng(w:2)) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
warning_mem = 70
critical_mem = 85

[[block]]
block = "sound"
show_volume_when_muted = true
headphones_indicator = true
#[[block.click]]
#button = "left"
#cmd = "pavucontrol"

[[block]]
block = "apt"
interval = 1800
ignore_phased_updates = true

[[block]]
block = "uptime"
format = " $text "
